# Generated by Django 5.0.4 on 2024-04-20 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weather', models.CharField(max_length=100)),
                ('temperature', models.IntegerField()),
                ('material', models.CharField(max_length=30)),
                ('occasion', models.CharField(max_length=30)),
                ('dress', models.CharField(max_length=30)),
                ('dress_type', models.CharField(max_length=30)),
            ],
        ),
    ]
