# Generated by Django 5.0.4 on 2024-04-20 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloth_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='img_loc',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
