# Generated by Django 5.0.4 on 2024-04-20 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloth_app', '0003_alter_images_img_loc'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Images',
            new_name='image',
        ),
    ]
