# Generated by Django 5.0.4 on 2024-04-20 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloth_app', '0004_rename_images_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='img_loc',
        ),
    ]
