# Generated by Django 5.0.4 on 2024-04-20 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloth_app', '0005_remove_image_img_loc'),
    ]

    operations = [
        migrations.DeleteModel(
            name='image',
        ),
    ]
